int('3.5')
#ValueErrorになる
        
